[project]
name = "pinn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepxde>=1.13.1",
    "kaleido==0.2.0",
    "plotly>=6.0.0",
    "torch>=2.6.0",
]
